services:
  - type: web
    name: auction-system
    runtime: docker
    plan: free
    buildCommand: docker build -t auction-system .
    startCommand: java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar app.jar
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: auction-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: auction-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: auction-db
          property: password

databases:
  - name: auction-db
    databaseName: auction_system
    user: auction_user
