# Production configuration
spring:
  profiles.active: prod
  thymeleaf.cache: true
  main.show-banner: false
  
  # Production Database Configuration (Environment variables)
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/Auction_System?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DATABASE_DRIVER:com.mysql.jdbc.Driver}
    
  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.MySQLDialect}
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: false
        jdbc:
          time_zone: Asia/Kolkata

# Server Configuration for Production
server:
  port: ${PORT:9090}
  session-timeout: 1800
  
# Logging for Production
logging:
  level:
    com.in: INFO
    org.hibernate: WARN
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
