CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    phone_number VARCHAR(20),
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    balance DECIMAL(19, 4) NOT NULL DEFAULT 0.0000,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
    starting_price DECIMAL(19, 4) NOT NULL,
    current_price DECIMAL(19, 4) NOT NULL,
    seller_id BIGINT NOT NULL REFERENCES users(user_id),
    winner_id BIGINT REFERENCES users(user_id),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    version BIGINT NOT NULL DEFAULT 0,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    starting_price DECIMAL(19, 2),
    reserve_price DECIMAL(19, 2),
    current_highest_bid DECIMAL(19, 2),
    status VARCHAR(50),
    image_url VARCHAR(500),
    auction_start_time TIMESTAMP,
    auction_end_time TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    seller_id BIGINT REFERENCES users(user_id),
    winner_id BIGINT REFERENCES users(user_id),
    auction_slot_id INT,
    version BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bids (
    bid_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    auction_id BIGINT REFERENCES auctions(id),
    listing_id BIGINT,
    bidder_id BIGINT REFERENCES users(user_id),
    buyer_id BIGINT REFERENCES users(user_id),
    amount DECIMAL(19, 4),
    bid_amount DECIMAL(19, 4),
    status VARCHAR(20) NOT NULL DEFAULT 'ACCEPTED',
    idempotency_key VARCHAR(100) UNIQUE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    bid_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auctions_status ON auctions(status);
CREATE INDEX IF NOT EXISTS idx_auctions_end_time ON auctions(end_time);
CREATE INDEX IF NOT EXISTS idx_bids_auction_id ON bids(auction_id);
CREATE INDEX IF NOT EXISTS idx_bids_bidder_id ON bids(bidder_id);
